{"uuid": "89265c70-b5ab-4bd7-9e5e-90dd0089ee99", "children": ["8c5cac40-c456-437f-a882-ffa0c7361d58"], "befores": [{"name": "start_appium_desired", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: 'noReset' must be of type boolean\nStacktrace:\nInvalidArgumentError: 'noReset' must be of type boolean\n    at validateCaps (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/capabilities.js:52:11)\n    at parseCaps (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/capabilities.js:154:20)\n    at processCapabilities (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/capabilities.js:199:43)\n    at parseCapsForInnerDriver (/usr/local/lib/node_modules/appium/lib/utils.js:112:21)\n    at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:290:26)\n    at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:330:9)\n    at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:344:15)\n    at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:496:26)\n    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:306:34)\n    at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:432:15\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)\n    at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)\n    at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)\n    at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)\n", "trace": "  File \"/Library/Python/3.8/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Python/3.8/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Python/3.8/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/weinancao/PycharmProjects/Appium_AutoTest/testcase/conftest.py\", line 34, in start_appium_desired\n    driver = appium_desired_caps(host, port,systemPort)\n  File \"/Users/weinancao/PycharmProjects/Appium_AutoTest/base/DesireCaps.py\", line 36, in appium_desired_caps\n    driver = webdriver.Remote('http://%s:%s/wd/hub'%(host,port), desired_caps)\n  File \"/Library/Python/3.8/site-packages/appium/webdriver/webdriver.py\", line 257, in __init__\n    super().__init__(\n  File \"/Library/Python/3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 206, in __init__\n    self.start_session(capabilities)\n  File \"/Library/Python/3.8/site-packages/appium/webdriver/webdriver.py\", line 346, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Library/Python/3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Python/3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1691584691312, "stop": 1691584697733}], "start": 1691584691312, "stop": 1691584697868}